const Actions = {
  ADD_PROJECT: 'ADD_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',

  ADD_TAG: 'ADD_TAG',
  UPDATE_TAG: 'UPDATE_TAG',
  DELETE_TAG: 'DELETE_TAG',

  ADD_TASK_ITEM: 'ADD_TASK_ITEM',
  UPDATE_TASK_ITEM: 'UPDATE_TASK_ITEM',
  DELETE_TASK_ITEM: 'DELETE_TASK_ITEM',
}

export default Actions;